apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: shift-manager
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/shiftmanager"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SERVER_SERVLET_CONTEXT_PATH: "/api"