server:
  port: 8080

spring:
  application:
    name: shift-manager-api
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME:shiftmanager@example.com}
  password: ${MAIL_PASSWORD:password}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
