# Server configuration
server:
  port: 8000
  servlet:
    context-path: /
  shutdown: graceful

# Spring configuration
spring:
  application:
    name: shift-manager

# Logging configuration
logging:
  level:
    root: INFO
    com.shiftmanager: INFO

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
