# Build stage
FROM node:18-alpine as build
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./web-client/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY ./web-client/ ./

# Build the application
RUN npm run build -- --configuration production

# Runtime stage
FROM nginx:alpine

# Copy the custom nginx.conf
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the build output
COPY --from=build /app/dist/web-client /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Run nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
