server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: shift-management-system
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
  liquibase:
    enabled: true
    change-log: classpath:db/master-changelog.yaml
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      default-view-inclusion: true
  security:
    user:
      name: admin
      password: admin
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: INFO
    com.shiftmanager: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

app:
  security:
    jwt:
      secret: ${JWT_SECRET:defaultsecret12345678901234567890}
      expiration: 86400000
  notification:
    email:
      enabled: true
      from: noreply@shiftmanager.com
    sms:
      enabled: false
  default-shift-types:
    - name: Day Shift
      startTime: 08:00:00
      endTime: 16:00:00
      shiftType: DAY
      breakDurationMinutes: 30
      isDefault: true
    - name: Evening Shift
      startTime: 16:00:00
      endTime: 00:00:00
      shiftType: EVENING
      breakDurationMinutes: 30
      isDefault: true
    - name: Night Shift
      startTime: 00:00:00
      endTime: 08:00:00
      shiftType: NIGHT
      breakDurationMinutes: 30
      isDefault: true
  reporting:
    export:
      pdf-enabled: true
      excel-enabled: true
